import { Filter, Plus, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import AdminLayout from '../../Layouts/AdminLayout';
import { BookingModal } from '../../Components/BookingModal';
import BookingDetailModal from '../../Components/BookingDetailModal';
import { StatusBadge } from '../../Components/UI';
import { useDemo } from '../../App';
import { peso, shortDate, timeLabel } from '../../Utils/format';

export default function BookingsPage(){const {bookings,addBooking,updateBooking}=useDemo();const [query,setQuery]=useState('');const [status,setStatus]=useState('All');const [adding,setAdding]=useState(false);const [selected,setSelected]=useState(null);const [editing,setEditing]=useState(null);const shown=useMemo(()=>bookings.filter((b)=>(status==='All'||b.status===status)&&`${b.customer} ${b.reference} ${b.mobile}`.toLowerCase().includes(query.toLowerCase())),[bookings,query,status]);const action=<button className="btn btn-primary" onClick={()=>setAdding(true)}><Plus/>Add booking</button>;return <AdminLayout title="Bookings" subtitle={`${bookings.length} reservations in the demo workspace`} action={action}><section className="panel"><div className="table-tools"><label><Search/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search name, mobile, or reference"/></label><div className="filter-select"><Filter/><select value={status} onChange={(e)=>setStatus(e.target.value)}>{['All','Pending','Confirmed','Completed','Cancelled','No-show'].map((s)=><option key={s}>{s}</option>)}</select></div></div><div className="data-table"><table><thead><tr><th>Booking</th><th>Customer</th><th>Schedule</th><th>Payment</th><th>Status</th><th/></tr></thead><tbody>{shown.map((b)=><tr key={b.id}><td><strong>{b.reference}</strong><small>{b.source}</small></td><td><strong>{b.customer}</strong><small>{b.mobile}</small></td><td><strong>{shortDate(b.date)}</strong><small>{timeLabel(b.start)} – {timeLabel(b.end)}</small></td><td><strong>{peso(b.amount)}</strong><StatusBadge value={b.paymentStatus}/></td><td><StatusBadge value={b.status}/></td><td><button onClick={()=>setSelected(b)}>View</button></td></tr>)}</tbody></table></div></section>{adding&&<BookingModal onClose={()=>setAdding(false)} onSave={(data)=>{addBooking({...data,duration:1,paid:data.paymentStatus==='Paid'?500:0});setAdding(false)}}/>}{editing&&<BookingModal initial={editing} onClose={()=>setEditing(null)} onSave={(data)=>{updateBooking(editing.id,data);setEditing(null);setSelected(null)}}/>}{selected&&<BookingDetailModal booking={selected} onClose={()=>setSelected(null)} onEdit={()=>setEditing(selected)} onUpdate={(changes)=>{updateBooking(selected.id,changes);setSelected({...selected,...changes})}}/>}</AdminLayout>}
