import { ArrowLeft, Check, Clock3, Copy, LockKeyhole, MapPin, QrCode, ShieldCheck, Users } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import PublicLayout from '../../Layouts/PublicLayout';
import { court, courtById } from '../../Data/court';
import { useDemo } from '../../App';
import { displayDate, endTime, peso, timeLabel } from '../../Utils/format';

export default function CheckoutPage() {
  const { draft, addBooking } = useDemo(); const navigate = useNavigate(); const [copied,setCopied] = useState(false); const [loading,setLoading]=useState(false); const [method,setMethod]=useState('QR Ph'); const selectedCourt = courtById(draft.courtId);
  const confirm = () => { setLoading(true); setTimeout(() => { addBooking({ courtId:draft.courtId, customer:draft.name, mobile:draft.mobile, email:draft.email, players:draft.players, date:draft.date, start:draft.start, duration:draft.duration, notes:draft.notes, paymentMethod:method, paid:250, paymentStatus:'Partially Paid', status:'Confirmed' }); navigate('/confirmation'); }, 850); };
  return <PublicLayout compact><div className="checkout-grid"><div><div className="flow-top"><Link to="/book/review"><ArrowLeft/> Back to review</Link><span><i/> STEP 4 OF 4</span></div><section className="checkout-summary"><div className="checkout-summary-title"><div><span className="eyebrow">RESERVATION SUMMARY</span><h2>{selectedCourt.name} ({selectedCourt.type})</h2></div><span>{draft.duration * 60} mins</span></div><div className="summary-panel"><p><Clock3/>{displayDate(draft.date)} • {timeLabel(draft.start)} – {timeLabel(endTime(draft.start))}</p><p><MapPin/>{court.location}</p><p><Users/>{draft.players} {draft.players === 1 ? 'player' : 'players'}</p><div><span>Rate: {peso(selectedCourt.hourlyRate)} / hr × {draft.duration} hr</span><strong>{peso(selectedCourt.hourlyRate)}</strong></div></div><div className="total-due"><span>Total due</span><strong>{peso(selectedCourt.hourlyRate)} <small>PHP</small></strong></div></section></div><section className="pay-card"><div className="pay-head"><div><span className="qr-brand">QR</span><span><strong>QR Ph</strong><small>National QR Standard</small></span></div><span className="expires"><Clock3/> Demo payment</span></div><div className="payment-tabs">{['QR Ph','GCash','Maya','Pay at Court'].map((m)=><button className={method===m?'active':''} onClick={()=>setMethod(m)} key={m}>{m}</button>)}</div>{method === 'Pay at Court' ? <div className="pay-later"><ShieldCheck/><h3>Reserve now, pay at Picklr</h3><p>Your booking will remain pending until the Picklr team confirms it.</p></div> : <><div className="fake-qr"><QrPattern/><span><QrCode/> Instant bank & e-wallet detection</span></div><div className="bank-pills"><span>GCash</span><span>Maya</span><span>BPI</span><span>BDO</span><span>UnionBank</span></div><div className="reference"><span><small>Reference number</small><strong>#PK-84920</strong></span><button onClick={() => {navigator.clipboard?.writeText('PK-84920');setCopied(true)}}>{copied?<Check/>:<Copy/>}{copied?'Copied':'Copy'}</button></div></>}<ol className="pay-steps"><strong>Simple steps</strong><li><span>1</span>Open your selected banking or e-wallet app.</li><li><span>2</span>Scan the code and enter the required deposit.</li><li><span>3</span>Confirm exactly <strong>{peso(250)}</strong>.</li></ol><button disabled={loading} className="btn btn-primary full" onClick={confirm}><ShieldCheck/>{loading?'Confirming demo booking…':method==='Pay at Court'?'Confirm reservation':'I have paid / Confirm booking'}</button><p className="secure-copy"><LockKeyhole/> Demo only — no real payment will be processed.</p></section></div></PublicLayout>;
}
function QrPattern(){return <svg viewBox="0 0 100 100" aria-label="Demo QR code"><rect width="100" height="100" rx="4" fill="white"/><path fill="#15191b" d="M8 8h26v26H8zm6 6v14h14V14zm52-6h26v26H66zm6 6v14h14V14zM8 66h26v26H8zm6 6v14h14V72zm28-62h8v8h-8zm12 0h6v7h-6zM40 25h8v8h-8zm12 10h8v8h-8zm-12 8h8v8h-8zm17 4h7v8h-7zm-17 12h8v8h-8zm12 2h8v8h-8zm15-20h8v8h-8zm12 2h8v8h-8zm-10 12h8v8h-8zm12 7h9v8h-9zM40 74h8v8h-8zm12 8h8v8h-8zm9-11h8v8h-8zm12 8h8v8h-8z"/><rect x="44" y="44" width="14" height="14" rx="2" fill="#15803d"/><circle cx="51" cy="51" r="3" fill="white"/></svg>}
