import { CalendarPlus, Check, Clock3, MapPin, Search } from 'lucide-react';
import { Link } from 'react-router-dom';
import PublicLayout from '../../Layouts/PublicLayout';
import { courtById } from '../../Data/court';
import { useDemo } from '../../App';
import { displayDate, peso, timeLabel } from '../../Utils/format';
import { StatusBadge } from '../../Components/UI';

export default function ConfirmationPage(){const {confirmation}=useDemo(); if(!confirmation)return <PublicLayout><div className="empty"><Search/><h2>No recent booking</h2><p>Start a reservation or look up an existing one.</p><Link className="btn btn-primary" to="/book">Book now</Link></div></PublicLayout>; const selectedCourt=courtById(confirmation.courtId); return <PublicLayout><div className="confirmation"><div className="success-mark"><Check/></div><span className="eyebrow">BOOKING CONFIRMED</span><h1>You’re all set, {confirmation.customer.split(' ')[0]}.</h1><p>We saved your Picklr court time and sent a demo confirmation summary.</p><section><small>BOOKING REFERENCE</small><strong className="booking-ref">{confirmation.reference}</strong><p>Keep this reference with your mobile number to manage the booking.</p><dl><div><dt><CalendarPlus/>Date</dt><dd>{displayDate(confirmation.date)}</dd></div><div><dt><Clock3/>Time</dt><dd>{timeLabel(confirmation.start)} – {timeLabel(confirmation.end)}</dd></div><div><dt><MapPin/>Court</dt><dd>{selectedCourt.name} • {selectedCourt.type}</dd></div><div><dt>Amount</dt><dd>{peso(confirmation.amount)}</dd></div><div><dt>Payment</dt><dd><StatusBadge value={confirmation.paymentStatus}/></dd></div></dl></section><div className="confirmation-actions"><Link className="btn btn-primary" to={`/booking/${confirmation.reference}/manage`}>View booking</Link><Link className="btn btn-secondary" to={`/booking/${confirmation.reference}/manage`}>Manage booking</Link><button className="btn btn-ghost" onClick={() => alert('Calendar file prepared — demo action complete.')}>Add to calendar</button></div></div></PublicLayout>}
