import { ArrowLeft, CalendarDays, Clock3, MapPin, Phone, RotateCcw, XCircle } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import PublicLayout from '../../Layouts/PublicLayout';
import { StatusBadge } from '../../Components/UI';
import { court, courtById } from '../../Data/court';
import { useDemo } from '../../App';
import { displayDate, peso, timeLabel } from '../../Utils/format';

export default function ManageBookingPage(){const {reference}=useParams();const {bookings,updateBooking}=useDemo();const b=bookings.find((x)=>x.reference===reference);if(!b)return <PublicLayout><div className="empty"><XCircle/><h2>Booking not found</h2><Link className="btn btn-primary" to="/booking/lookup">Try another reference</Link></div></PublicLayout>;const selectedCourt=courtById(b.courtId);return <PublicLayout><div className="manage-page"><Link className="back-link" to="/booking/lookup"><ArrowLeft/>Booking lookup</Link><div className="manage-head"><div><span className="eyebrow">BOOKING {b.reference}</span><h1>Your reservation</h1></div><div><StatusBadge value={b.status}/><StatusBadge value={b.paymentStatus}/></div></div><section className="manage-card"><div><CalendarDays/><span><small>Date</small><strong>{displayDate(b.date)}</strong></span></div><div><Clock3/><span><small>Time</small><strong>{timeLabel(b.start)} – {timeLabel(b.end)}</strong></span></div><div><MapPin/><span><small>Court</small><strong>{selectedCourt.name} • {selectedCourt.type}</strong><em>{court.location}</em></span></div><div><span><small>Amount</small><strong>{peso(b.amount)}</strong><em>{peso(b.paid)} recorded • {b.paymentMethod}</em></span></div>{b.notes&&<div className="notes-box"><small>Notes</small><p>{b.notes}</p></div>}</section><div className="manage-actions"><button className="btn btn-secondary" onClick={()=>alert('Choose another open time from the schedule — demo reschedule action.') }><RotateCcw/>Reschedule</button><button className="btn btn-danger" disabled={b.status==='Cancelled'} onClick={()=>updateBooking(b.id,{status:'Cancelled'})}><XCircle/>Cancel booking</button></div><p className="help-line"><Phone/>Need help? Call {court.phone}</p></div></PublicLayout>}
