server {
    listen 80;
    listen [::]:80;
    server_name splitshare.jmgaming.site;

    client_max_body_size 32m;
    resolver 127.0.0.11 ipv6=off valid=10s;
    set $splitshare_upstream splitshare-nginx-1:80;
    set $splitshare_reverb splitshare-reverb-1:8080;

    location / {
        proxy_pass http://$splitshare_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_redirect off;
    }

    location ^~ /app/ {
        proxy_pass http://$splitshare_reverb;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name jmgaming.site www.jmgaming.site;

    root /var/www/html/public;
    index index.php index.html;
    charset utf-8;
    client_max_body_size 32m;

    resolver 127.0.0.11 ipv6=off valid=10s;
    set $php_upstream php:9000;
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /dbadmin.php {
        auth_basic "ALAS DB Admin";
        auth_basic_user_file /etc/nginx/secrets/dbadmin.htpasswd;

        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass $php_upstream;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_param HTTPS on;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;
        fastcgi_param HTTP_X_FORWARDED_PORT 443;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass $php_upstream;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_param HTTPS on;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;
        fastcgi_param HTTP_X_FORWARDED_PORT 443;
    }

    location ~ /\. {
        deny all;
    }
}
