"""add receipt paths to finance records

Revision ID: 035a1d523d57
Revises: 74aed189c8b2
Create Date: 2026-08-12 14:23:23.382533
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035a1d523d57'
down_revision: str | Sequence[str] | None = '74aed189c8b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('receipt_storage_path', sa.String(length=500), nullable=True))
    op.add_column('settlements', sa.Column('receipt_storage_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settlements', 'receipt_storage_path')
    op.drop_column('expenses', 'receipt_storage_path')
    # ### end Alembic commands ###
