"""add tracker messages

Revision ID: 46d7251d26d4
Revises: 5fbfa4dcb54f
Create Date: 2026-08-12 12:02:21.216324
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d7251d26d4'
down_revision: str | Sequence[str] | None = '5fbfa4dcb54f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tracker_id', sa.UUID(), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracker_messages_tracker_created', 'tracker_messages', ['tracker_id', 'created_at'], unique=False)
    op.execute("ALTER TABLE public.tracker_messages ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tracker_messages_active_member_read
        ON public.tracker_messages FOR SELECT TO authenticated
        USING (
          EXISTS (
            SELECT 1 FROM public.tracker_members
            WHERE tracker_members.tracker_id = tracker_messages.tracker_id
              AND tracker_members.user_id = auth.uid()
              AND tracker_members.status = 'active'
          )
        )
        """
    )
    op.execute("ALTER PUBLICATION supabase_realtime ADD TABLE public.tracker_messages")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tracker_messages_tracker_created', table_name='tracker_messages')
    op.execute("ALTER PUBLICATION supabase_realtime DROP TABLE public.tracker_messages")
    op.execute("DROP POLICY IF EXISTS tracker_messages_active_member_read ON public.tracker_messages")
    op.drop_table('tracker_messages')
    # ### end Alembic commands ###
