"""add core collaboration and finance tables

Revision ID: 5fbfa4dcb54f
Revises: 20260812_01
Create Date: 2026-08-12 10:47:44.450279
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5fbfa4dcb54f"
down_revision: str | Sequence[str] | None = "20260812_01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tracker_id", sa.UUID(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("subject_type", sa.String(length=100), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tracker_id"], ["trackers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_activity_logs_tracker_created",
        "activity_logs",
        ["tracker_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tracker_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("icon_key", sa.String(length=100), nullable=True),
        sa.Column("is_system", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tracker_id"], ["trackers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_active_tracker_category_slug",
        "categories",
        ["tracker_id", "slug"],
        unique=True,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_table(
        "settlements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tracker_id", sa.UUID(), nullable=False),
        sa.Column("from_user_id", sa.UUID(), nullable=False),
        sa.Column("to_user_id", sa.UUID(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("settlement_date", sa.Date(), nullable=False),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount_minor > 0", name="ck_settlements_amount_positive"),
        sa.CheckConstraint("from_user_id <> to_user_id", name="ck_settlements_distinct_users"),
        sa.CheckConstraint("version >= 1", name="ck_settlements_version"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["from_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["to_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tracker_id"], ["trackers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_settlements_tracker_pair",
        "settlements",
        ["tracker_id", "from_user_id", "to_user_id"],
        unique=False,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_table(
        "tracker_invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tracker_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("email_normalized", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=30), server_default="viewer", nullable=False),
        sa.Column("status", sa.String(length=30), server_default="pending", nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("invited_by", sa.UUID(), nullable=False),
        sa.Column("accepted_by", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("declined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'editor', 'commenter', 'viewer')", name="ck_tracker_invitations_role"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'declined', 'revoked', 'expired')",
            name="ck_tracker_invitations_status",
        ),
        sa.CheckConstraint("expires_at > created_at", name="ck_tracker_invitations_expiry"),
        sa.ForeignKeyConstraint(["accepted_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["invited_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tracker_id"], ["trackers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tracker_invitations_email_normalized",
        "tracker_invitations",
        ["email_normalized"],
        unique=False,
    )
    op.create_index(
        "idx_tracker_invitations_status", "tracker_invitations", ["status"], unique=False
    )
    op.create_index(
        "uq_pending_tracker_invitation",
        "tracker_invitations",
        ["tracker_id", "email_normalized"],
        unique=True,
        postgresql_where="status = 'pending'",
    )
    op.create_table(
        "expenses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tracker_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("paid_by_user_id", sa.UUID(), nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount_minor > 0", name="ck_expenses_amount_positive"),
        sa.CheckConstraint("version >= 1", name="ck_expenses_version"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["paid_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tracker_id"], ["trackers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_expenses_paid_by_user_id", "expenses", ["paid_by_user_id"], unique=False)
    op.create_index(
        "idx_expenses_tracker_active",
        "expenses",
        ["tracker_id", "expense_date"],
        unique=False,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_table(
        "expense_splits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("expense_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_minor > 0", name="ck_expense_splits_amount_positive"),
        sa.ForeignKeyConstraint(["expense_id"], ["expenses.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_expense_splits_user_id", "expense_splits", ["user_id"], unique=False)
    op.create_index(
        "uq_expense_splits_expense_user", "expense_splits", ["expense_id", "user_id"], unique=True
    )
    op.drop_constraint(op.f("device_tokens_user_id_fkey"), "device_tokens", type_="foreignkey")
    op.drop_constraint(op.f("ck_device_tokens_platform"), "device_tokens", type_="check")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_device_tokens_platform"),
        "device_tokens",
        # The database's existing constraint expression is intentionally preserved.  # noqa: E501
        "platform::text = ANY (ARRAY['android'::character varying, 'ios'::character varying, 'web'::character varying]::text[])",  # noqa: E501
    )
    op.create_foreign_key(
        op.f("device_tokens_user_id_fkey"),
        "device_tokens",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index("uq_expense_splits_expense_user", table_name="expense_splits")
    op.drop_index("idx_expense_splits_user_id", table_name="expense_splits")
    op.drop_table("expense_splits")
    op.drop_index(
        "idx_expenses_tracker_active", table_name="expenses", postgresql_where="deleted_at IS NULL"
    )
    op.drop_index("idx_expenses_paid_by_user_id", table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(
        "uq_pending_tracker_invitation",
        table_name="tracker_invitations",
        postgresql_where="status = 'pending'",
    )
    op.drop_index("idx_tracker_invitations_status", table_name="tracker_invitations")
    op.drop_index("idx_tracker_invitations_email_normalized", table_name="tracker_invitations")
    op.drop_table("tracker_invitations")
    op.drop_index(
        "idx_settlements_tracker_pair",
        table_name="settlements",
        postgresql_where="deleted_at IS NULL",
    )
    op.drop_table("settlements")
    op.drop_index(
        "uq_active_tracker_category_slug",
        table_name="categories",
        postgresql_where="deleted_at IS NULL",
    )
    op.drop_table("categories")
    op.drop_index("idx_activity_logs_tracker_created", table_name="activity_logs")
    op.drop_table("activity_logs")
    # ### end Alembic commands ###
