"""create trackers and members

Revision ID: 74e01a3b79df
Revises: 20260811_01
Create Date: 2026-08-11 17:23:30.039028
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74e01a3b79df"
down_revision: str | Sequence[str] | None = "20260811_01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trackers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("currency_exponent", sa.SmallInteger(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="active", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "char_length(currency_code) = 3", name="ck_trackers_currency_code_length"
        ),
        sa.CheckConstraint(
            "currency_exponent BETWEEN 0 AND 4", name="ck_trackers_currency_exponent"
        ),
        sa.CheckConstraint("version >= 1", name="ck_trackers_version"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_trackers_created_at", "trackers", ["created_at"], unique=False)
    op.create_index("idx_trackers_deleted_at", "trackers", ["deleted_at"], unique=False)
    op.create_index("idx_trackers_owner_user_id", "trackers", ["owner_user_id"], unique=False)
    op.create_index("idx_trackers_status", "trackers", ["status"], unique=False)
    op.create_table(
        "tracker_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tracker_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="active", nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("removed_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'active' AND removed_at IS NULL) OR "
            "(status = 'removed' AND removed_at IS NOT NULL)",
            name="ck_tracker_members_removed_state",
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'editor', 'commenter', 'viewer')", name="ck_tracker_members_role"
        ),
        sa.CheckConstraint("status IN ('active', 'removed')", name="ck_tracker_members_status"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["removed_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tracker_id"], ["trackers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_tracker_members_user_id", "tracker_members", ["user_id"], unique=False)
    op.create_index(
        "uq_active_tracker_membership",
        "tracker_members",
        ["tracker_id", "user_id"],
        unique=True,
        postgresql_where="status = 'active'",
    )
    op.create_index(
        "uq_active_tracker_owner",
        "tracker_members",
        ["tracker_id"],
        unique=True,
        postgresql_where="role = 'owner' AND status = 'active'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_active_tracker_owner",
        table_name="tracker_members",
        postgresql_where="role = 'owner' AND status = 'active'",
    )
    op.drop_index(
        "uq_active_tracker_membership",
        table_name="tracker_members",
        postgresql_where="status = 'active'",
    )
    op.drop_index("idx_tracker_members_user_id", table_name="tracker_members")
    op.drop_table("tracker_members")
    op.drop_index("idx_trackers_status", table_name="trackers")
    op.drop_index("idx_trackers_owner_user_id", table_name="trackers")
    op.drop_index("idx_trackers_deleted_at", table_name="trackers")
    op.drop_index("idx_trackers_created_at", table_name="trackers")
    op.drop_table("trackers")
    # ### end Alembic commands ###
